/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FormNilai extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        ulang();
        tampil_cb();
    }
    PreparedStatement pst;
    ResultSet rs;
    Connection conn = new koneksi().getKoneksi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tBind = new javax.swing.JTextField();
        tBingg = new javax.swing.JTextField();
        tIpa = new javax.swing.JTextField();
        tMtk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tNim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNilai = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        cNik = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Form Input Nilai UN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Bahasa Indonesia");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Bahasa Inggris");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("IPA");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Matematika");

        tBind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBindActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("NIM");

        tNim.setBackground(new java.awt.Color(204, 204, 204));
        tNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNimKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNimKeyTyped(evt);
            }
        });

        tableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNilai);

        jLabel11.setText("Cari Berdasarkan NIK :");

        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });

        bSimpan.setBackground(new java.awt.Color(102, 255, 102));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHitung.setBackground(new java.awt.Color(204, 255, 204));
        bHitung.setText("HITUNG");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 0, 51));
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(0, 204, 255));
        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bUlang.setBackground(new java.awt.Color(204, 255, 255));
        bUlang.setText("ULANG");
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tNim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(tMtk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tIpa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tBingg, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tBind, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(bHitung))
                            .addComponent(cNik, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSimpan)
                            .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bUlang))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tBind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tBingg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tIpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tMtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bHitung))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bHapus)
                                    .addComponent(bUbah)))
                            .addComponent(bUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public void tampil_cb(){
       try{
           String sql = "SELECT * FROM siswa";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {                
                cNik.addItem(rs.getString("nik"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        } catch (SQLException e) {
       }
        
    }
    
    private void tampil_data(){
        try{
            String[]judul = {"NIK","Bahasa Indonesia","Bahasa Inggris","IPA","Matematika","NEM"};
            DefaultTableModel dtm = new DefaultTableModel(null,judul);
            tableNilai.setModel(dtm);
            String sql = "";
            if(tCari.getText().isEmpty()){
                sql= "select * from nilai";
            }else{
                sql = "select * from nilai where nik like '%"+tCari.getText()+"%'";
            }
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String[]data={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(FormPendaftaran.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    private void tBindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBindActionPerformed

    private void tNimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNimKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNimKeyPressed

    private void tNimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNimKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tNimKeyTyped
    private void ulang(){
    tBind.setText("");
    tBingg.setText("");
    tIpa.setText("");
    tMtk.setText("");
    tNim.setText("");
    tNim.setEditable(false);
    tampil_data();
    }
    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed

    private void tableNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNilaiMouseClicked
        // TODO add your handling code here:
        int baris = tableNilai.getSelectedRow();
        String nik = tableNilai.getValueAt(baris, 0).toString();
        if(!nik.isEmpty()){
            cNik.setSelectedItem(nik);
            tBind.setText(tableNilai.getValueAt(baris, 1).toString());
            tBingg.setText(tableNilai.getValueAt(baris, 2).toString());
            tIpa.setText(tableNilai.getValueAt(baris, 3).toString());
            tMtk.setText(tableNilai.getValueAt(baris, 4).toString());
            tNim.setText(tableNilai.getValueAt(baris, 5).toString());
            bUbah.setEnabled(true);
            bHapus.setEnabled(true);
            bSimpan.setEnabled(false);
    }                                      
    }//GEN-LAST:event_tableNilaiMouseClicked

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
               if(tNim.getText().isEmpty()||cNik.getSelectedItem().toString().isEmpty()){   
        JOptionPane.showMessageDialog(null,"Inputan Data Anda Tidak Boleh Kosong!!!");
        }else{
            try{
                pst = conn.prepareStatement("insert into nilai values(?,?,?,?,?,?)");
                pst.setString(1, cNik.getSelectedItem().toString());
                pst.setString(2, tBind.getText());
                pst.setString(3, tBingg.getText());
                pst.setString(4, tIpa.getText());
                pst.setString(5, tMtk.getText());
                pst.setString(6, tNim.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Nilai Berhasil Telah Disimpan!");
                ulang();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Data Nilai Gagal Ditambahkan!!!" + ex.toString());
                Logger.getLogger(FormPendaftaran.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
               tampil_cb();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
               float bhs_ind,bhs_ingg,ipa,mtk,nim;
        
        bhs_ind = Float.parseFloat(tBind.getText());
        bhs_ingg = Float.parseFloat(tBingg.getText());
        ipa = Float.parseFloat(tIpa.getText());
        mtk = Float.parseFloat(tMtk.getText());
        nim = (bhs_ind + bhs_ingg + ipa + mtk)*10/100;
        
        tNim.setText(Float.toString(nim));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Data ini ?","Hapus Data?",JOptionPane.YES_NO_OPTION);
        if(hapus==0){
            try{
                String sql ="delete from nilai where nik=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cNik.getSelectedItem().toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Pendaftaran Berhasil Telah Di Hapus!");
                ulang();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Data Pendaftaran Gagal Di Hapus!!!" + ex.toString());
                Logger.getLogger(FormPendaftaran.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
                int ubah = JOptionPane.showConfirmDialog(null,"Anda Ingin Merubah Data ini ?","Ubah Data?",JOptionPane.YES_NO_OPTION);
        if(ubah==0){
            try{
                String sql ="update nilai set nik=?,bahasa_indonesia=?,bahasa_inggris=?,ipa=?,mtk=?,nim=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cNik.getSelectedItem().toString());
                pst.setString(2, tBind.getText());
                pst.setString(3, tBingg.getText());
                pst.setString(4, tIpa.getText());
                pst.setString(5, tMtk.getText());
                pst.setString(6, tNim.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Nilai Berhasil Di Ubah!");
                ulang();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Data Nilai Gagal Dirubah!!!" + ex.toString());
                Logger.getLogger(FormPendaftaran.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_bUlangActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        tampil_data();
    }//GEN-LAST:event_tCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton bUlang;
    private javax.swing.JComboBox<String> cNik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBind;
    private javax.swing.JTextField tBingg;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIpa;
    private javax.swing.JTextField tMtk;
    private javax.swing.JTextField tNim;
    private javax.swing.JTable tableNilai;
    // End of variables declaration//GEN-END:variables

    
}
